language: python

python:
  #  - "3.6"
  - "3.7"
  #  - "3.8"
  - "nightly"  # future python

# windows test dropped as they were too unreliable (2020/04/18)

install:
  # additional dependencies just for testing (mostly pytest)
  - pip3 install pipenv
  - pipenv install --dev

script:
  # `python -m` appends current path to PYTHONPATH, `pytest` would not find app.solver
  # import from app.* (absolute paths) for both files and modules needed
  - python -m pytest
