dist: xenial
os: linux
language: python

python:
  - "3.7"
  #  - "3.8"
  # - "nightly"  # future python

# windows test dropped as they were too unreliable (2020/04/18)

install:
  # additional dependencies just for testing (mostly pytest)
  - pip3 install pipenv
  - pipenv install --dev

# --- test everything

script:
  # `python -m` appends current path to PYTHONPATH, `pytest` would not find app.solver
  # import from app.* (absolute paths) for both files and modules needed
  - python -m pytest

# --- deploy to docker

services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKERHUB_USER}/cutsolver
    - IMAGE_NAME_TAGGED=${DOCKERHUB_USER}/cutsolver:${TRAVIS_TAG}

after_success:
  # build once for every deploy, updating both latest and adding a tag
  - docker build --tag ${IMAGE_NAME}:latest IMAGE_NAME_TAGGED .

deploy:
  - provider: script
    script:
      docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW} && docker push ${IMAGE_NAME}
    on:
      branch: master
      tags: true
