dist: xenial
os: linux
language: python

python:
  - "3.7"
  #  - "3.8"
  # - "nightly"  # future python

# windows test dropped as they were too unreliable (2020/04/18)

services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKERHUB_USER}/cutsolver
    - IMAGE_NAME_TAGGED=${DOCKERHUB_USER}/cutsolver:${TRAVIS_TAG}

stages:
  - test
  - name: deploy to docker hub
    # tag = v0.1[.2[.3]]
    # TRAVIS SETS BRANCH = TAG if TAG != ""!
    # deploy is bad, multi-arch is needed and not working well right now
    # see c27cc27b and surrounding commits for a cleaner amd64 only solution
    if: tag =~ ^v([0-9]+.)+[0-9]$ AND fork = false AND type = push


jobs:
  include:
    - stage: test
      install:
        # additional dependencies just for testing (mostly pytest)
        - pip3 install pipenv
        - pipenv install --dev

      script:
        # `python -m` appends current path to PYTHONPATH, `pytest` would not find app.solver
        # import from app.* (absolute paths) for both files and modules needed
        - python -m pytest
        - echo "$TRAVIS_EVENT_TYPE | $TRAVIS_BRANCH | $TRAVIS_TAG"

    - stage: deploy to docker hub
      script:
        - source ./multi-arch-docker-ci.sh
        - travis_wait 40 multi_arch_docker::main
        # script:
        # build once for every deploy, updating both latest and adding a tag
        # takes forever, might timeout travis
        # - travis_wait 20 docker buildx build --platform linux/amd64,linux/arm/v7 --tag ${IMAGE_NAME}:latest --tag ${IMAGE_NAME_TAGGED} .
