version: '3'

services:

  cutsolver:
    build: .
    # image: modischfabrications/cutsolver:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 1m
      timeout: 5s
